import {describe,it,expect} from 'vitest'
import {readFileSync} from 'node:fs'
import {runInNewContext} from 'node:vm'
const {JSDOM}=require('jsdom')
const html=readFileSync('public/groups.html','utf8')
function fn(name:string){const start=html.indexOf('  function '+name+'('),at=html.indexOf('{',start);let depth=1,end=at+1;for(;depth;end++){if(html[end]==='{')depth++;if(html[end]==='}')depth--}return html.slice(start,end)}
function setup(n:number){const document=new JSDOM(html.replace(/<style[\s\S]*?<\/style>/g,'').replace(/<script[\s\S]*?<\/script>/g,'')).window.document;const c:any={document,QUEUE:Array(n).fill({}),BLOCKS:[{count:n,price:1234,includedUnlocks:n/4}],targetBundle:()=>n,reviewItems:()=>Array.from({length:n},(_,i)=>({effectId:'e'+(n-i)})),effectLabel:(id:string)=>'Name '+id,ASPECTS:[{id:'3:2',label:'Landscape'}],ASPECT:null,priceOf:(s:any)=>s.price,usd:(p:number)=>'$'+p};runInNewContext(fn('paintGroupsCart'),c);return c}
describe('Groups cart summary',()=>{
 it.each([4,8,16])('uses actual slot order and package for %s artworks',n=>{const c=setup(n);c.paintGroupsCart();expect(c.document.getElementById('groupsCartCount').textContent).toBe(n+' artworks');expect(Array.from(c.document.querySelectorAll('#groupsCartEffects li')).map((e:any)=>e.textContent)).toEqual(Array.from({length:n},(_,i)=>'Name e'+(n-i)));expect(c.document.getElementById('groupsShapeSummary').textContent).toContain('$1234');expect(c.document.getElementById('groupsShapeSummary').textContent).toContain(n/4+' Unlock');expect(c.document.getElementById('groupsCartBack').textContent).toBe('← Back to Discovery')})
 it('shows selected Format only on Format and returns to Review',()=>{const c=setup(4);c.document.body.classList.add('groups-shapes');c.paintGroupsCart();expect(c.document.getElementById('groupsCartFormat').hidden).toBe(true);c.ASPECT='3:2';c.paintGroupsCart();expect(c.document.getElementById('groupsCartFormat').textContent).toBe('Format · Landscape');expect(c.document.getElementById('groupsCartFormat').hidden).toBe(false);expect(c.document.getElementById('groupsCartBack').textContent).toBe('← Back to Review');c.document.body.classList.remove('groups-shapes');c.paintGroupsCart();expect(c.document.getElementById('groupsCartFormat').hidden).toBe(true)})
 it('removes redundant instructions and retains six existing formats and final action',()=>{const c=setup(4);expect(c.document.getElementById('groupsJourney')).toBe(null);expect(c.document.querySelector('#groupsShapes .aspect-gallery__say')).toBe(null);expect(c.document.getElementById('groupsShapeRail').textContent).not.toContain('One Last Choice');expect(c.document.getElementById('groupsShapeCraft').textContent).toBe('Craft My Collection')})
})
