// lib/v1/portraits/effect-registry.ts
//
// ─────────────────────────────────────────────────────────────────────────────
// CENG-OWNED. SINGLE SOURCE OF TRUTH FOR THE EFFECT CATALOG.
//
// Do not edit this file in the CUI or CC lanes. Do not edit the generated
// public/effect-registry.js by hand — it is overwritten.
//
// After ANY edit here, run:   node scripts/emit-effect-registry.js
//
// Why this file exists: CUI's standalone HTML keyed its effect lists on
// DISPLAY LABELS with HTML entities baked in ("Frost &amp; Ice"), while the
// engine keys on snake_case ids. Those two can never be joined, and each lane
// was maintaining its own parallel list. This is the contract between them.
// ─────────────────────────────────────────────────────────────────────────────

export type SiloId =
  | 'earth_ore'
  | 'artists_gallery'
  | 'light_glass'
  | 'myth_legend'
  | 'far_future'
  | 'another_age'
  | 'living_world'
  | 'handmade'

/** 'live'     — body + avoid are in the engine NOW; safe to offer and spend on.
 *  'authored' — text exists (see the CENG carryover) but is NOT yet entered
 *               into the engine. The gate will refuse it. Do not offer.
 *  'todo'     — not written.                                                  */
export type BodyStatus = 'live' | 'authored' | 'todo'

/** Likeness gate band. Thresholds are NOT set — pull the bench fidelity-score
 *  distribution and set them from real data before this is wired.             */
export type LikenessFloor = 'strict' | 'relaxed' | 'bypass'

export interface Silo {
  id:    SiloId
  label: string
  /** Curator's line on entering the room. CUI draft register; CENG to finalize. */
  line:  string
}

export interface Effect {
  id:       string          // snake_case. Matches the engine preset/effect id EXACTLY.
  label:    string          // customer-facing. Plain unicode — no HTML entities.
  category: SiloId

  mode:       'material' | 'costume'
  monolithic: boolean       // true → takes HUE_LOCK (one substance, one hue family)

  body:   BodyStatus
  refs:   number            // ref plates shot and approved, 0-3
  /** Per-effect framing override. Absent = 'bust'.                            */
  framing?:      'bust' | 'signature' | 'statuesque'
  likenessFloor: LikenessFloor
  /** Effect carries its own light source; drop the STAGING paragraph.         */
  skipStaging?:  boolean
  /** Effect owns its own composition; skip the universal framing block.       */
  skipUniversal?: boolean
  /** Gendered ref plates (2_man / 2_woman / 2_neutral) rather than neutral.
   *  UNDER REVIEW — a deliberately diverse neutral set may remove the need.   */
  genderedRefs?: boolean

  /** Not customer-facing. Carried so the lanes stop re-deriving it. */
  note?: string
}

// ── SILOS ────────────────────────────────────────────────────────────────────

export const SILOS: Silo[] = [
  { id:'earth_ore',      label:'Earth & Ore',
    line:'Here are the Earth & Ore finishes. Weight, grain, and the honesty of real material.' },
  { id:'artists_gallery', label:'The Artists Gallery',
    line:'Here are the Artists Gallery finishes. A maker\u2019s hand, left visible.' },
  { id:'light_glass',    label:'Light & Glass',
    line:'Here are the Light & Glass finishes. Translucent, and lit from within.' },
  { id:'myth_legend',    label:'Myth & Legend',
    line:'Here are the Myth & Legend finishes. For a sitting with some nerve to it.' },
  { id:'far_future',     label:'Far & Future',
    line:'Here are the Far & Future finishes. Cool metals and further horizons.' },
  { id:'another_age',    label:'Another Age',
    line:'Here are the Another Age finishes. A sitting in a century not your own.' },
  { id:'living_world',   label:'Living World',
    line:'Here are the Living World finishes. Grown rather than made.' },
  { id:'handmade',       label:'Handmade',
    line:'Here are the Handmade finishes. Softer work, and made by hand.' },
]

// ── EFFECTS ──────────────────────────────────────────────────────────────────
// 56 slots. See EFFECTS-REVISION-2026-07-29.md for adds/drops/moves and reasons.

export const EFFECTS: Effect[] = [

  // ── earth_ore ─────────────────────────────────────────────────────────────
  { id:'bronze',    label:'Bronze',       category:'earth_ore', mode:'material', monolithic:true,  body:'live', refs:1, likenessFloor:'strict' },
  { id:'iron',      label:'Iron',         category:'earth_ore', mode:'material', monolithic:true,  body:'live', refs:1, likenessFloor:'strict' },
  { id:'stone',     label:'Quartzite',    category:'earth_ore', mode:'material', monolithic:true,  body:'live', refs:1, likenessFloor:'strict',
    note:'LABEL CHANGED from Stone. id stays `stone` — renaming touches PortraitsPresetId, PRESET_LABELS, STYLE_MATERIALS, Pass 2. Pass 2 debt: its refinement text still describes rough-chiseled stone; contradicts polished quartzite. Inert (Pass 2 off) — rewrite before enabling.' },
  { id:'alabaster', label:'Alabaster',    category:'earth_ore', mode:'material', monolithic:true,  body:'live', refs:1, likenessFloor:'strict',
    note:'Translucent — needs the anti-ageing clause pair (smoothed facial surface + bright alert eyes). Do NOT use an SSS/transmission clause; it produced orange nose and ear artifacts three times.' },
  { id:'jade',      label:'Carved Jade',  category:'earth_ore', mode:'material', monolithic:true,  body:'authored', refs:2, likenessFloor:'strict',
    note:'NEW — replaces pewter. Matte/waxy nephrite lustre, not glassy jadeite. SSS must be bound: pale and stone-toned, ears do not light up, light originates outside the piece.' },
  { id:'ebony',     label:'Ebony',        category:'earth_ore', mode:'material', monolithic:true,  body:'live', refs:1, likenessFloor:'strict',
    note:'Needs a light background for silhouette separation, plus a fill light at half key or the face goes unreadable.' },
  { id:'walnut',    label:'Walnut',       category:'earth_ore', mode:'material', monolithic:true,  body:'live', refs:1, likenessFloor:'strict',
    note:'The "clearly lighter and warmer than ebony" clause is load-bearing — without it walnut and ebony are indistinguishable at thumbnail size.' },

  // ── artists_gallery ───────────────────────────────────────────────────────
  { id:'impressionist',   label:'Impressionist',      category:'artists_gallery', mode:'material', monolithic:false, body:'live', refs:1, likenessFloor:'strict',
    note:'Polychrome, hue-lock exempt. Specifies a ROUND plinth, unlike Earth & Ore\u2019s dark block. Artists tails bake their own staging — LOCATION is a no-op.' },
  { id:'watercolour',     label:'Watercolour',        category:'artists_gallery', mode:'material', monolithic:false, body:'authored', refs:1, likenessFloor:'relaxed',
    note:'NEW — replaces torn_paper. Fills the transparent-pigment gap. SPELLING IS AN ID: watercolour, UK. Do not let it drift to watercolor.' },
  { id:'folded_book',     label:'Folded Book',        category:'artists_gallery', mode:'material', monolithic:true,  body:'live', refs:1, likenessFloor:'strict',
    note:'Engine tail includes "Visible printed text" — kept in the engine, DROPPED for the ref plate (garbled type). Ref and engine deliberately diverge.' },
  { id:'charcoal_chalk',  label:'Charcoal & Chalk',   category:'artists_gallery', mode:'material', monolithic:true,  body:'live', refs:1, likenessFloor:'strict' },
  { id:'sheet_music',     label:'Sheet Music',        category:'artists_gallery', mode:'material', monolithic:false, body:'live', refs:1, likenessFloor:'strict',
    note:'Notation stays legible — that is the effect. No no-text clause.' },
  { id:'driftwood_resin', label:'Driftwood & Resin',  category:'artists_gallery', mode:'material', monolithic:false, body:'live', refs:1, likenessFloor:'strict',
    note:'Required an explicit skin ban naming face/neck/forehead/ears — two attempts produced skin with wood texture.' },
  { id:'pencil_sketch',   label:'Pencil Sketch',      category:'artists_gallery', mode:'material', monolithic:true,  body:'live', refs:0, likenessFloor:'strict', skipUniversal:true,
    note:'skipUniversal — owns its own side-angle asymmetric composition. Ref prompt must be authored specially, NOT from the standard template.' },

  // ── light_glass ───────────────────────────────────────────────────────────
  // OPEN: cast_glass in or out? Silo is at 7 without dichroic_glass, 8 with.
  { id:'cast_glass',      label:'Cast Glass',         category:'light_glass', mode:'material', monolithic:false, body:'authored', refs:0, likenessFloor:'relaxed',
    note:'OPEN DECISION — in or out. Closest neighbour to blown_glass. Carries the canonical anti-ageing clause pair; copy it to the other four translucents.' },
  { id:'blown_glass',     label:'Blown Glass',        category:'light_glass', mode:'material', monolithic:false, body:'live', refs:2, likenessFloor:'relaxed',
    note:'Needs the anti-ageing clause pair.' },
  { id:'stained_glass',   label:'Stained Glass',      category:'light_glass', mode:'material', monolithic:false, body:'live', refs:0, likenessFloor:'relaxed',
    note:'MOVED from artists_gallery — it is glass.' },
  { id:'amber',           label:'Amber',              category:'light_glass', mode:'material', monolithic:true,  body:'live', refs:0, likenessFloor:'relaxed',
    note:'Needs the anti-ageing clause pair.' },
  { id:'ice',             label:'Frost & Ice',        category:'light_glass', mode:'material', monolithic:true,  body:'authored', refs:2, likenessFloor:'relaxed',
    note:'Frost tracery settles into wrinkles — needs the anti-ageing pair most of the five. Ref problems: 1_man.jpg is a female child; rename and replace with an adult male plate or it pulls subjects younger and fights the age lock.' },
  { id:'mercury',         label:'Liquid Mercury',     category:'light_glass', mode:'material', monolithic:true,  body:'live', refs:0, likenessFloor:'relaxed' },
  { id:'fantasy_crystal', label:'Enchanted Crystal',  category:'light_glass', mode:'material', monolithic:false, body:'live', refs:0, likenessFloor:'relaxed',
    note:'Needs the anti-ageing clause pair.' },
  { id:'dichroic_glass',  label:'Dichroic Glass',     category:'light_glass', mode:'material', monolithic:false, body:'todo', refs:0, likenessFloor:'relaxed',
    note:'Enters only if cast_glass leaves. Colour-shifting coated glass, hue flips with viewing angle.' },

  // ── myth_legend ───────────────────────────────────────────────────────────
  { id:'dragon_skin',      label:'Dragon Skin',      category:'myth_legend', mode:'material', monolithic:false, body:'live', refs:0, likenessFloor:'strict' },
  { id:'fire_face',        label:'Fire & Ember',     category:'myth_legend', mode:'costume',  monolithic:false, body:'authored', refs:3, likenessFloor:'strict', skipStaging:true,
    note:'FOLDER RENAME REQUIRED: public/style-refs/portraits/fire-face -> fire_face. A hyphen loads zero refs, silently. skipStaging — refs are lit by the fire, conflicting with the mandated gallery key. First costume effect whose refs are photoreal people rather than sculpture: check register against the gallery line.' },
  { id:'magic_energy',     label:'Magic Energy',     category:'myth_legend', mode:'material', monolithic:false, body:'live', refs:0, likenessFloor:'relaxed',
    note:'Overlaps cosmic and nebula_resin. Compare all three before locking.' },
  { id:'armor',            label:'Living Armor',     category:'myth_legend', mode:'costume',  monolithic:false, body:'live', refs:0, likenessFloor:'strict' },
  { id:'reclaimed_bronze', label:'Reclaimed Bronze', category:'myth_legend', mode:'material', monolithic:false, body:'live', refs:0, likenessFloor:'strict',
    note:'DUPLICATE FLAG vs bronze in earth_ore. Different silos makes it worse, not better. Compare side by side; if they read the same to a customer, cut one.' },
  { id:'golden_idol',      label:'Golden Idol',      category:'myth_legend', mode:'material', monolithic:true,  body:'todo', refs:0, likenessFloor:'strict' },
  { id:'runestone',        label:'Runestone',        category:'myth_legend', mode:'material', monolithic:true,  body:'todo', refs:0, likenessFloor:'strict' },

  // ── far_future ────────────────────────────────────────────────────────────
  { id:'retro_robot',   label:'Atomic Age Robot',  category:'far_future', mode:'material', monolithic:false, body:'authored', refs:2, likenessFloor:'strict',
    note:'Ref cleanup required before use: both plates carry garbled signage (crop it out — refs outrank text); the plates disagree on clothing (pick fabric-garment-in-metal); rename 1_girl.jpg -> 2_woman.jpg and do not add an age axis.' },
  { id:'cosmic',        label:'Cosmic Bloom',      category:'far_future', mode:'costume',  monolithic:false, body:'authored', refs:2, likenessFloor:'relaxed', genderedRefs:true,
    note:'Overlaps nebula_resin and magic_energy hard. Compare all three before locking. Refs were found misfiled under a fantasy_elf folder and moved 2026-07-30 — they are galaxy portraits, not elves.' },
  { id:'nebula_resin',  label:'Nebula Resin',      category:'far_future', mode:'material', monolithic:false, body:'live', refs:0, likenessFloor:'relaxed' },
  { id:'neon',          label:'Neon Drawing',      category:'far_future', mode:'material', monolithic:false, body:'live', refs:0, likenessFloor:'relaxed' },
  { id:'volume_light',  label:'Volumetric Light',  category:'far_future', mode:'material', monolithic:false, body:'authored', refs:3, likenessFloor:'bypass', skipStaging:true,
    note:'MOVED from light_glass — reads as energy, not material. TESTED AND WORKING: do not edit the body. bypass floor — a form dissolving into tendrils fails strict scoring even when excellent, and silently burns retries.' },
  { id:'wireframe',     label:'Wireframe Model',   category:'far_future', mode:'material', monolithic:false, body:'todo', refs:0, likenessFloor:'relaxed',
    note:'Glowing vector lines over dark; form described by edges rather than surfaces. The one place loss of surface detail is the point.' },
  { id:'digital_human', label:'Digital Human',     category:'far_future', mode:'material', monolithic:false, body:'todo', refs:2, likenessFloor:'relaxed',
    note:'Replaces the unwritten `hologram` slot 2026-07-30. Refs already shot (1.jpg, 2.jpg) — body still to author.' },

  // ── another_age ───────────────────────────────────────────────────────────
  // All costume, all likeness-preserving. Gendered refs: a doublet and a gown
  // are genuinely different garments.
  { id:'elizabethan',   label:'Elizabethan Portrait', category:'another_age', mode:'costume', monolithic:false, body:'live', refs:3, likenessFloor:'strict', genderedRefs:true,
    note:'DECIDED: 3D render, NOT painting. The Holbein / Horenbout / Teerlinc / Toto / Penni direction is dead. Needs the thoughtful EXPRESSION_BLOCK — the mandated settled smile overrode neutral-period in one of three test outputs.' },
  { id:'renaissance',   label:'Renaissance Portrait', category:'another_age', mode:'costume', monolithic:false, body:'todo', refs:0, likenessFloor:'strict', genderedRefs:true },
  { id:'deco_twenties', label:'Deco Twenties',        category:'another_age', mode:'costume', monolithic:false, body:'todo', refs:0, likenessFloor:'strict', genderedRefs:true },
  { id:'victorian',     label:'Victorian Portrait',   category:'another_age', mode:'costume', monolithic:false, body:'todo', refs:0, likenessFloor:'strict', genderedRefs:true,
    note:'REWRITE, not a first draft — the old body was cut for failing. Root cause: costume mode strips the material anchor, leaving nothing to resist NB2\u2019s photographic prior. FIX: the body must name a MEDIUM (hand-tinted photograph, oil portrait, albumen print), not just "Victorian styling". Same fix that made elizabethan work. Ensure CC does not resurrect the old body.' },
  { id:'samurai',       label:'Samurai',              category:'another_age', mode:'costume', monolithic:false, body:'todo', refs:0, likenessFloor:'strict', genderedRefs:true,
    note:'Will drift toward ethnic recasting of the subject\u2019s features. The avoid MUST block this explicitly or it is a support problem, not a portrait.' },
  { id:'wild_west',     label:'Wild West',            category:'another_age', mode:'costume', monolithic:false, body:'todo', refs:0, likenessFloor:'strict', genderedRefs:true },
  { id:'ancient_egypt', label:'Ancient Egypt',        category:'another_age', mode:'costume', monolithic:false, body:'todo', refs:0, likenessFloor:'strict', genderedRefs:true,
    note:'Same ethnic-recasting risk as samurai. Block explicitly.' },

  // ── living_world ──────────────────────────────────────────────────────────
  { id:'coral',          label:'Living Reef',    category:'living_world', mode:'material', monolithic:false, body:'authored', refs:2, likenessFloor:'strict', framing:'statuesque',
    note:'MOVED from myth_legend. framing statuesque is load-bearing — hands are specified and every universal forbids them under bust. Refs: source + brain-coral texture plate (the smoothed-face anchor) + one composition plate. DROP the reef-environment plate: no figure, pulls composition toward landscape.' },
  { id:'flowing_water',  label:'Flowing Water',  category:'living_world', mode:'material', monolithic:false, body:'todo', refs:2, likenessFloor:'relaxed',
    note:'Historically failed. Root cause identical to volume_light: "made of water" reads as "wet person". The body MUST say the water IS the structure and the silhouette breaks into spray and droplets.' },
  { id:'frozen_splash',  label:'Frozen Splash',  category:'living_world', mode:'material', monolithic:false, body:'todo', refs:0, likenessFloor:'relaxed',
    note:'The easier of the two water effects — a caught splash has real form to hold a likeness. Build this one first.' },
  { id:'moss_stone',     label:'Moss & Stone',   category:'living_world', mode:'material', monolithic:false, body:'todo', refs:0, likenessFloor:'strict' },
  { id:'blossom',        label:'Blossom',        category:'living_world', mode:'material', monolithic:false, body:'todo', refs:0, likenessFloor:'relaxed' },
  { id:'autumn_leaf',    label:'Autumn Leaf',    category:'living_world', mode:'material', monolithic:false, body:'todo', refs:0, likenessFloor:'relaxed' },
  { id:'butterfly_wing', label:'Butterfly Wing', category:'living_world', mode:'material', monolithic:false, body:'todo', refs:0, likenessFloor:'relaxed' },

  // ── handmade ──────────────────────────────────────────────────────────────
  // Absorbs the old curiosities silo. Gendered refs — garment-driven.
  { id:'plushy',     label:'Plushy',        category:'handmade', mode:'material', monolithic:false, body:'live', refs:0, likenessFloor:'relaxed', genderedRefs:true },
  { id:'chocolate',  label:'Chocolate',     category:'handmade', mode:'material', monolithic:true,  body:'live', refs:0, likenessFloor:'strict',  genderedRefs:true },
  { id:'balloon',    label:'Balloon',       category:'handmade', mode:'material', monolithic:false, body:'todo', refs:2, likenessFloor:'relaxed', genderedRefs:true,
    note:'Replaces the unwritten `origami` slot 2026-07-30 — Folded Paper overlapped folded_book too heavily. Refs already shot.' },
  { id:'mosaic',     label:'Tile Mosaic',   category:'handmade', mode:'material', monolithic:false, body:'todo', refs:0, likenessFloor:'strict',  genderedRefs:true },
  { id:'topiary',    label:'Living Topiary', category:'handmade', mode:'material', monolithic:true, body:'todo', refs:0, likenessFloor:'relaxed', genderedRefs:true },
  { id:'wicker',     label:'Woven Wicker',  category:'handmade', mode:'material', monolithic:true,  body:'todo', refs:0, likenessFloor:'strict',  genderedRefs:true },
  { id:'melted_wax', label:'Melted Wax',    category:'handmade', mode:'material', monolithic:true,  body:'todo', refs:3, likenessFloor:'relaxed',
    note:'Replaces the unwritten `embroidery` slot 2026-07-30 — embroidery overlapped plushy. Refs already shot (3 plates, neutral).' },
]

// ── POSE / EXPRESSION ────────────────────────────────────────────────────────
// One pose applies to the whole queue. Replaces the EXPRESSION paragraph in
// STUDIO_DIRECTIVES / COSTUME_DIRECTIVES at the same tier position — it CANNOT
// be appended, because the mandated settled smile overrides anything appended
// after it.

export interface Pose {
  id:       string
  label:    string
  /** Keeps the source expression. NOT the source camera angle — reinstating
   *  the snapshot framing brings back the flat passport look that was
   *  deliberately removed. Expression only.                                   */
  preserve?: boolean
  note?:    string
}

export const POSES: Pose[] = [
  { id:'as_photographed', label:'Keep My Pose', preserve:true,
    note:'EXPRESSION ONLY. Must not reinstate the source camera angle or framing.' },
  { id:'smiling',    label:'Smiling'    },
  { id:'laughing',   label:'Laughing'   },
  { id:'thoughtful', label:'Thoughtful' },
  { id:'dramatic',   label:'Dramatic'   },
  { id:'goofy',      label:'Goofy',
    note:'Fights the museum register on stone and bronze — will read as a broken render. Consider handmade-only, or relabel Playful.' },
]

// ── DERIVED HELPERS ──────────────────────────────────────────────────────────

/** Safe to offer and spend credits on. Replaces CUI's hand-maintained
 *  NO_ENGINE list, which went stale the moment a body landed. */
export const isOfferable = (e: Effect): boolean => e.body === 'live'

export const effectsBySilo = (silo: SiloId): Effect[] =>
  EFFECTS.filter(e => e.category === silo)

export const offerableBySilo = (silo: SiloId): Effect[] =>
  effectsBySilo(silo).filter(isOfferable)

export const byId = (id: string): Effect | undefined =>
  EFFECTS.find(e => e.id === id)
