#!/usr/bin/env python3
"""
Patch pets-catalog-35.ts - revise 8 locked effect bodies.
Keys: plushy, stone, alabaster, clown, pencil_sketch, samurai, neon, porcelain.
Source of new text: pets-prompts-catalog.md (Rich, 30 Aug 2026).

Dry-run by default. Use --apply to write.
"""
import sys, argparse, shutil, datetime

TARGET = r'lib/v1/pets/pets-catalog-35.ts'

REPLACEMENTS = [
    (
        "  plushy: {\n    id:    'plushy',\n    label: 'Plushy',\n    body: `Transform the entire animal into an adorable, soft, slightly overstuffed handmade plush toy, preserving strong facial likeness while gently idealizing the animal’s attractiveness and warmth. Give the face a sweet, lovable expression, softly flattering proportions and a subtle friendly smile without becoming cartoonish. Very soft fabric, visible paw stitching, gently uneven seams and cuddly compression. Clothing carries through entirely in soft knitted and stuffed materials.\nFrame tightly from mid-chest to head, with the animal filling most of the image. Nestle and gently squish them into a cozy pile of well-loved teddy bears, stuffed animals and pillows, with plush toys affectionately pressing against their shoulders and withers and entering the edges of frame.\nSet the scene on a rumpled bed at night with a warm bedside lamp and generous soft fill. Golden light keeps the face bright and flattering, with creamy bedding, soft open shadows and rich tactile detail. Lovable, cuddly, safe and deeply comforting, like a treasured childhood plush tucked into bed with all its friends.\nNo letters or held objects. Complete full-body sculpture: the whole animal from nose to tail to paws, nothing omitted, simplified or cropped. IF THE ANIMAL IS A HORSE OR OTHER LARGE ANIMAL, frame the head and neck only - a full horse at this scale leaves the head too small to recognise. THE MARKINGS ARE THE LIKENESS - preserve their pattern, placement and proportion exactly, because they do for an animal what facial structure does for a person. The animal's head occupies about 20% of the image. A collar and tags carry through in the same material and are welcome; they are identity, not props. Preserve breed, build, age and natural asymmetry. Add nothing that is not in the source.`,\n  },\n",
        "  plushy: {\n    id:    'plushy',\n    label: 'Plushy',\n    body: `Transform the pet into an expensive handmade plush toy, preserving facial likeness, breed, build, eye color and exact markings. Use short, dense, uniform luxury plush fabric. No individual hairs, wisps, flyaways, ear tufts, furry edges, realistic whiskers or feather detail. Clean sewn silhouettes; markings appear as color patterns in fabric, never natural fur. Softly stuffed face, rounded paws, subtle seams and stitching. Nestle into teddy bears and pillows on a rumpled bed at night, warm bedside lamp, creamy bedding, cozy golden light. Clearly a plush replica, never a real animal. reduce the hair, fur and feathers to a simplified pet plushy. no real hair, fur or feathers. no text.`,\n  },\n",
        'plushy',
    ),
    (
        "  stone: {\n    id:    'stone',\n    label: 'Stone',\n    body: `make the animal into a realistic carved Taj Mahal quartzite sculpture — warm ivory-to-honey stone with soft translucent depth and fine gold-brown veining. Roughly a sixth of the piece is still raw quarry stone — irregular grey mottled rock with a fractured, unhewn face — running along the bottom edge and up the right side to about halfway, so the carved figure reads as emerging from the block it was cut from. The transition is abrupt, a chisel line between finished and raw. Nothing stands behind the figure — no slab, wall or backing panel; the sculpture is free-standing against the background. Subtle subsurface scattering: light diffuses just beneath the polished surface, warming the thinnest sections softly. The scattering stays pale and stone-toned — never orange, never a bright glow, and the ears do not light up. Hard directional key light from the upper left with deep shadow across the right half of the face and strong falloff. Professional magazine-cover photography. No letters, no plaque. The face is carved in the cleanest part of the matrix — smooth, evenly toned, no veining crossing the eyes, nose or muzzle. Concentrate veining in the collar and shoulders and withers. The entire sculpture is quartzite — no other materials, no real fur, feathers, scales or claws. Background: a conservatory at dusk — cast-iron ribs, rain on glass, cool green light, heavily out of focus. The sculpture stands on a cast-iron plant stand. THE PIECE IS STONE, NOT A COLOURED ANIMAL. No fur colour, no eye colour, no coat colour survives - the markings read as tone and mineral variation WITHIN the stone and nothing else. At most a 15% warm tint across the whole sculpture; anything more and it stops being carved and starts being painted. Complete full-body sculpture: the whole animal from nose to tail to paws, nothing omitted, simplified or cropped. IF THE ANIMAL IS A HORSE OR OTHER LARGE ANIMAL, frame the head and neck only - a full horse at this scale leaves the head too small to recognise. THE MARKINGS ARE THE LIKENESS - preserve their pattern, placement and proportion exactly, because they do for an animal what facial structure does for a person. The animal's head occupies about 20% of the image. A collar and tags carry through in the same material and are welcome; they are identity, not props. Preserve breed, build, age and natural asymmetry. Add nothing that is not in the source.`,\n  },\n",
        "  stone: {\n    id:    'stone',\n    label: 'Stone',\n    body: `Sculpt the pet entirely from one continuous mass of Taj Mahal quartzite. Every visible surface, including face, ears, muzzle, paws and tail, is polished or carved stone. Absolutely no real fur, hair, feathers, scales, skin or animal surface texture. Preserve breed, build, age, facial structure and the exact MAP of coat/feather markings; markings are essential to likeness, but exist ONLY as subtle mineral tone and veining within the quartzite. Warm ivory-honey stone, gold-brown veins, ≤15% pet-color tint. Raw quarry stone ~1/6 bottom/right. Conservatory dusk, iron stand, hard upper-left light. NO REAL HAIR, FUR, SKIN or SCALES!`,\n  },\n",
        'stone',
    ),
    (
        "  alabaster: {\n    id:    'alabaster',\n    label: 'Alabaster',\n    body: `Transform the animal into a carved translucent alabaster sculpture with warm subsurface scattering, milky stone depth, soft glowing edges, faint amber veining, polished and semi-translucent high points, and deeper cloudy opacity in thicker areas. The ENTIRE animal including coat, ears, muzzle, tail and paws is rendered in this same translucent alabaster; the animal's markings are expressed as deeper cloudy veining and tonal shifts within the stone, following the exact pattern of the source coat so the markings remain readable while the whole sculpture stays alabaster. THE PIECE IS STONE, NOT A COLOURED ANIMAL. No fur colour, no eye colour, no coat colour survives - the markings read as veining and tone WITHIN the stone and nothing else. At most a 15% warm tint across the whole sculpture; anything more and it stops being carved and starts being painted. Soft directional light raking across the form so the translucency reads, deep shadow on the far side, strong falloff. Photographic and highly idealised - a real carved object in real light. Background: a quiet gallery alcove, warm stone and shadow, heavily out of focus. Complete full-body sculpture: the whole animal from nose to tail to paws, nothing omitted, simplified or cropped. IF THE ANIMAL IS A HORSE OR OTHER LARGE ANIMAL, frame the head and neck only - a full horse at this scale leaves the head too small to recognise. THE MARKINGS ARE THE LIKENESS - preserve their pattern, placement and proportion exactly, because they do for an animal what facial structure does for a person. The animal's head occupies about 20% of the image. A collar and tags carry through in the same material and are welcome; they are identity, not props. Preserve breed, build, age and natural asymmetry. Add nothing that is not in the source.`,\n  },\n",
        "  alabaster: {\n    id:    'alabaster',\n    label: 'Alabaster',\n    body: `Transform the animal into a carved translucent alabaster sculpture with warm subsurface scattering, milky stone depth, soft glowing edges, faint amber veining, polished and semi-translucent high points, and deeper cloudy opacity in thicker areas. The ENTIRE animal including coat, ears, muzzle, tail and paws is rendered in this same translucent alabaster; the animal's markings are expressed as deeper cloudy veining and tonal shifts within the stone, following the exact pattern of the source coat so the markings remain readable while the whole sculpture stays alabaster. THE PIECE IS STONE, NOT A COLOURED ANIMAL. No fur colour, no eye colour, no coat colour survives - the markings read as veining and tone WITHIN the stone and nothing else. At most a 15% warm tint across the whole sculpture; anything more and it stops being carved and starts being painted. Soft directional light raking across the form so the translucency reads, deep shadow on the far side, strong falloff. Photographic and highly idealised - a real carved object in real light. Background: a quiet gallery alcove, warm stone and shadow, heavily out of focus. Complete full-body sculpture: the whole animal from nose to tail to paws, nothing omitted, simplified or cropped. IF THE ANIMAL IS A HORSE OR OTHER LARGE ANIMAL, frame the head and neck only - a full horse at this scale leaves the head too small to recognise. THE MARKINGS ARE THE LIKENESS - preserve their pattern, placement and proportion exactly, because they do for an animal what facial structure does for a person. The animal's head occupies about 15% of the image. A collar and tags carry through in the same material and are welcome; they are identity, not props. Preserve breed, build, age and natural asymmetry. Add nothing that is not in the source. show light shining through the stone in places that are thinner\nNo real skin, hair, fur, or scales. Simplify the coat of the animal to simulate being carved from stone. tint the stone by 20% to match pets skin, hair, fur, scale pattern.`,\n  },\n",
        'alabaster',
    ),
    (
        "  clown: {\n    id:    'clown',\n    label: 'Clown',\n    body: `Transform the animal into a grand circus clown, preserving its breed, build and markings precisely. A ruffled collar in bold primary silk sits at the throat, a small conical hat with a pom-pom perches between the ears, and a round red nose caps the muzzle. Soft greasepaint in white, red and black follows the animal's OWN markings rather than covering them - the pattern it already has, picked out in paint. No costume over the body; the coat stays the coat. Warm theatrical light from a single spot above, deep falloff into a darkened big-top interior, tiered seating and rigging out of focus behind. Rich saturated reds, whites and gold. Photographic and highly idealised - a real animal in real light, dignified and delighted rather than mocked. Complete full-body sculpture: the whole animal from nose to tail to paws, nothing omitted, simplified or cropped. IF THE ANIMAL IS A HORSE OR OTHER LARGE ANIMAL, frame the head and neck only - a full horse at this scale leaves the head too small to recognise. THE MARKINGS ARE THE LIKENESS - preserve their pattern, placement and proportion exactly, because they do for an animal what facial structure does for a person. The animal's head occupies about 20% of the image. A collar and tags carry through in the same material and are welcome; they are identity, not props. Preserve breed, build, age and natural asymmetry. Add nothing that is not in the source.`,\n    avoid: `Avoid a sad or frightened expression. Avoid a full-body costume or clothing. Avoid painting over the animal's natural markings. Avoid horror or menace.`,\n  },\n",
        "  clown: {\n    id:    'clown',\n    label: 'Clown',\n    body: `Transform the animal into a circle de soleil clown, preserving its breed, build and markings precisely. A ruffled collar in muted tones in silk sits at the throat, a small conical hat with a large pom-pom in same colors perches between the ears, and a round red nose caps the muzzle. Soft greasepaint in white, and ruffle colors follows the animal's OWN markings rather than covering them, around the eyes, nose and mouth - the pattern it already has, picked out in paint. costume over the body; Warm theatrical light from a single spot above, deep falloff into a darkened big-top interior, tiered seating and rigging out of focus behind. Photographic and highly idealised - a real animal in real light, dignified and delighted rather than mocked. Complete full-body sculpture: the whole animal from nose to tail to paws, nothing omitted, simplified or cropped. IF THE ANIMAL IS A HORSE OR OTHER LARGE ANIMAL, frame the head and neck only - a full horse at this scale leaves the head too small to recognise. THE MARKINGS ARE THE LIKENESS - preserve their pattern, placement and proportion exactly, because they do for an animal what facial structure does for a person. The animal's head occupies about 20% of the image. A collar and tags carry through in the same material and are welcome; they are identity, not props. Preserve breed, build, age and natural asymmetry. Add nothing that is not in the source.`,\n    avoid: `Avoid a sad or frightened expression. Avoid a full-body costume or clothing. Avoid painting over the animal's natural markings. Avoid horror or menace.`,\n  },\n",
        'clown',
    ),
    (
        "  pencil_sketch: {\n    id:    'pencil_sketch',\n    label: 'Pencil Sketch',\n    body: `A solid sculpted bust of the animal carved entirely from graphite — soft pencil-lead grey with a burnished sheen, the surface worked in visible pencil strokes that wrap the form: crosshatching in the recesses, broad shading across the planes, edges softly smudged. Eyes and lips are graphite. No coat, no real coat. The collar carries through in the same material. A real object standing in real light, casting its own shadow. Set in a beautiful old-world artist's atelier — dark timber, plaster walls, antique easels, stacked canvases and old studies pinned around the room, a huge ribbed skylight above flooding it with soft daylight. Monochrome throughout. Likeness is critical. Complete full-body sculpture: the whole animal from nose to tail to paws, nothing omitted, simplified or cropped. IF THE ANIMAL IS A HORSE OR OTHER LARGE ANIMAL, frame the head and neck only - a full horse at this scale leaves the head too small to recognise. THE MARKINGS ARE THE LIKENESS - preserve their pattern, placement and proportion exactly, because they do for an animal what facial structure does for a person. The animal's head occupies about 20% of the image. A collar and tags carry through in the same material and are welcome; they are identity, not props. Preserve breed, build, age and natural asymmetry. Add nothing that is not in the source.`,\n    avoid: `Avoid a drawing on paper, an easel-mounted picture or any flat image. Avoid a duplicated face. Avoid colour.`,\n  },\n",
        "  pencil_sketch: {\n    id:    'pencil_sketch',\n    label: 'Pencil Sketch',\n    body: `A solid sculpted bust of the animal carved entirely from graphite — hard pencil-lead grey with a burnished sheen, the surface worked in visible pencil strokes that wrap the form: crosshatching in the recesses, broad shading across the planes, edges softly smudged. Eyes and lips are graphite. No coat, no real coat. The collar carries through in the same material. A real object standing in real light, casting its own shadow. Monochrome throughout. Likeness is critical. Complete full-body sculpture: the whole animal from nose to tail to paws, nothing omitted, simplified or cropped. IF THE ANIMAL IS A HORSE OR OTHER LARGE ANIMAL, frame the head and neck only - a full horse at this scale leaves the head too small to recognise. THE MARKINGS ARE THE LIKENESS - preserve their pattern, placement and proportion exactly, because they do for an animal what facial structure does for a person. The animal's head occupies about 20% of the image. A collar and tags carry through in the same material and are welcome; they are identity, not props. Preserve breed, build, age and natural asymmetry. Add nothing that is not in the source.\nSet in a beautiful old-world artist's atelier — dark timber, plaster walls, antique easels, stacked canvases and old studies pinned around the room, a huge ribbed skylight above flooding it with soft daylight. the background is in full color`,\n    avoid: `Avoid a drawing on paper, an easel-mounted picture or any flat image. Avoid a duplicated face. Avoid colour.`,\n  },\n",
        'pencil_sketch',
    ),
    (
        "  samurai: {\n    id:    'samurai',\n    label: 'Samurai',\n    body: `Professional cinematic portrait of a male samurai in authentic Edo-period armor, layered red lacquered lamellar plates and thick silk lacing, with the convincing weight, wear and imperfection of real historical armor. Hair naturally arranged beneath the helmet.\nuse foreshortening and strong dynamic lighting. age the photo with filters. reduce saturation on coat tones.\nStrong late-afternoon sunlight sweeps across it from the side, sculpting the face and armor with luminous highlights and deep expressive shadows.\nPhotographic realism with the richness and visual poetry of a great painted portrait — atmospheric, tactile and subtly painterly without becoming an illustration. Rich restrained color, beautiful falloff, shallow depth of field, softly impressionistic Japanese setting. Idealized and striking while remaining completely believable as a photograph. Preserve facial likeness and permanent features. Complete full-body sculpture: the whole animal from nose to tail to paws, nothing omitted, simplified or cropped. IF THE ANIMAL IS A HORSE OR OTHER LARGE ANIMAL, frame the head and neck only - a full horse at this scale leaves the head too small to recognise. THE MARKINGS ARE THE LIKENESS - preserve their pattern, placement and proportion exactly, because they do for an animal what facial structure does for a person. The animal's head occupies about 20% of the image. A collar and tags carry through in the same material and are welcome; they are identity, not props. Preserve breed, build, age and natural asymmetry. Add nothing that is not in the source.`,\n  },\n",
        "  samurai: {\n    id:    'samurai',\n    label: 'Samurai',\n    body: `Professional cinematic portrait of the pet as a samurai in authentic Edo-period armor, layered red lacquered lamellar plates and thick silk lacing, with the convincing weight, wear and imperfection of real historical armor. Hair naturally arranged beneath the helmet. use foreshortening and strong dynamic lighting. age the photo with filters. reduce saturation on coat tones. Strong late-afternoon sunlight sweeps across it from the side, sculpting the face and armor with luminous highlights and deep expressive shadows. Photographic realism with the richness and visual poetry of a great painted portrait — atmospheric, tactile and subtly painterly without becoming an illustration. Rich restrained color, beautiful falloff, shallow depth of field, softly impressionistic Japanese setting. Idealized and striking while remaining completely believable as a photograph. Preserve facial likeness and permanent features. Complete full-body sculpture: the whole animal from nose to tail to paws, nothing omitted, simplified or cropped. IF THE ANIMAL IS A HORSE OR OTHER LARGE ANIMAL, frame the head and neck only - a full horse at this scale leaves the head too small to recognise. THE MARKINGS ARE THE LIKENESS - preserve their pattern, placement and proportion exactly, because they do for an animal what facial structure does for a person. The animal's head occupies about 20% of the image. A collar and tags carry through in the same material and are welcome; they are identity, not props. Preserve breed, build, age and natural asymmetry. Add nothing that is not in the source.`,\n  },\n",
        'samurai',
    ),
    (
        "  neon: {\n    id:    'neon',\n    label: 'Neon',\n    body: `highly detailed neon tube sculpture. fully 3d in all three directions. implied volume. use negative space. use monochromate blues with variations on value. mounted in a small shops storefront window at night, rain on the glass, the shop dark behind. wires and electrical lines visible. at least 100 tubes Complete full-body sculpture: the whole animal from nose to tail to paws, nothing omitted, simplified or cropped. IF THE ANIMAL IS A HORSE OR OTHER LARGE ANIMAL, frame the head and neck only - a full horse at this scale leaves the head too small to recognise. THE MARKINGS ARE THE LIKENESS - preserve their pattern, placement and proportion exactly, because they do for an animal what facial structure does for a person. The animal's head occupies about 20% of the image. A collar and tags carry through in the same material and are welcome; they are identity, not props. Preserve breed, build, age and natural asymmetry. Add nothing that is not in the source.`,\n  },\n",
        "  neon: {\n    id:    'neon',\n    label: 'Neon',\n    body: `highly detailed neon tube sculpture. fully 3d in all three directions. implied volume. use negative space. use monochromate blues with variations on value. mounted in a small shops storefront window at night, rain on the glass, the shop dark behind. wires and electrical lines visible. at least 200 tubes Complete full-body sculpture: the whole animal from nose to tail to paws, nothing omitted, simplified or cropped. IF THE ANIMAL IS A HORSE OR OTHER LARGE ANIMAL, frame the head and neck only - a full horse at this scale leaves the head too small to recognise. THE MARKINGS ARE THE LIKENESS - preserve their pattern, placement and proportion exactly, because they do for an animal what facial structure does for a person. The animal's head occupies about 20% of the image. A collar and tags carry through in the same material and are welcome; they are identity, not props. Preserve breed, build, age and natural asymmetry. Add nothing that is not in the source.\nnew york diner open in behind the neon window sign`,\n  },\n",
        'neon',
    ),
    (
        "  porcelain: {\n    id:    'porcelain',\n    label: 'Porcelain',\n    body: `The animal is modelled in glazed porcelain — fine white clay, paw-thrown and kiln-fired, with a soft glassy glaze pooling in the hollows and thinning to near-white on the raised planes. Hand-painted cobalt blue decoration runs across the collar and shoulders and withers in small repeating floral motifs, the brushwork slightly uneven as a real paw leaves it. Fine crazing across the glaze, a chip at one edge, the unglazed foot showing raw biscuit. The face is porcelain throughout, glaze catching a single soft highlight on the cheek and brow. Likeness is critical and comes before the material. Photographic and highly idealized — a real fired object in real light, beautifully made. Background: a potter's shelf, other pieces out of focus behind, north light. Preserve natural facial character, asymmetry, lines and scars. Complete full-body sculpture: the whole animal from nose to tail to paws, nothing omitted, simplified or cropped. IF THE ANIMAL IS A HORSE OR OTHER LARGE ANIMAL, frame the head and neck only - a full horse at this scale leaves the head too small to recognise. THE MARKINGS ARE THE LIKENESS - preserve their pattern, placement and proportion exactly, because they do for an animal what facial structure does for a person. The animal's head occupies about 20% of the image. A collar and tags carry through in the same material and are welcome; they are identity, not props. Preserve breed, build, age and natural asymmetry. Add nothing that is not in the source.`,\n    avoid: `Avoid changing the hair. Avoid a plastic or resin look — this is fired clay under glaze. Avoid decoration crossing the face. Avoid real skin or hair.`,\n  },\n",
        "  porcelain: {\n    id:    'porcelain',\n    label: 'Porcelain',\n    body: `the sculpture should be the full size of the animal. Model the pet entirely in fine glazed porcelain, preserving its natural colors and exact markings as hand-painted underglaze beneath a clear glassy finish. No default blue-and-white palette. Pet likeness, breed, build, age, facial structure, eye color and marking placement are critical. Fine crazing, glaze pooling in hollows, subtle handmade irregularity, tiny chip, raw biscuit at foot. Collar/tags remain in porcelain. Potter's shelf, soft north light. Real fired object, never a real animal. Place the porcelain in a delicate wooden shipping box with antique travel labels. the insde of the box has fine straw positioned around the sculpture to protect it in transit. its a grandmothers treasure passed on. the background is a fine china shop at night.`,\n  },\n",
        'porcelain',
    ),
]

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--apply', action='store_true')
    ap.add_argument('--target', default=TARGET)
    args = ap.parse_args()

    with open(args.target, 'r', encoding='utf-8', newline='') as f:
        text = f.read()

    original = text
    for old, new, key in REPLACEMENTS:
        count = text.count(old)
        if count == 0:
            print(f'REFUSE: anchor not found for {key} (0 matches) - file may have drifted')
            sys.exit(1)
        if count > 1:
            print(f'REFUSE: anchor for {key} matches {count} times, expected 1')
            sys.exit(1)
        if new in text:
            print(f'SKIP: {key} already patched')
            continue
        text = text.replace(old, new, 1)
        print(f'OK: {key} patched')

    if text == original:
        print('No changes to make. Nothing written.')
        return

    if not args.apply:
        print()
        print('DRY RUN - no file written. Re-run with --apply to write.')
        return

    ts = datetime.datetime.now().strftime('%Y%m%d-%H%M%S')
    backup = args.target + f'.bak-{ts}'
    shutil.copy2(args.target, backup)
    print(f'Backup written: {backup}')

    with open(args.target, 'w', encoding='utf-8', newline='') as f:
        f.write(text)

    with open(args.target, 'r', encoding='utf-8', newline='') as f:
        verify = f.read()
    if verify != text:
        print('POST-WRITE VERIFY FAILED - file does not match intended content')
        sys.exit(1)
    for old, new, key in REPLACEMENTS:
        if new not in verify:
            print(f'POST-WRITE VERIFY FAILED - {key} not found in written file')
            sys.exit(1)
    print('Post-write verify OK. All 8 effects patched.')

if __name__ == '__main__':
    main()
