// lib/v1/landscapes/landscape-plaque.ts
//
// Plaque mode resolution + prompt-fragment assembly.
//
// Three modes:
//   off  — no plaque on the plinth at all
//   user — render the user's exact text (after metadata sanitization)
//   ai   — NB2 composes a title at render time following the carryover rules
//
// In all modes, metadata-shaped strings (timestamps, filenames, "Screenshot",
// technical strings, file extensions) are forbidden from reaching the plaque
// — this is the rule that fixes the "Screenshot 2026-04-22 063114" plaques
// the previous autoPlaque was producing.
//
// AI mode is implemented in-prompt via NB2's instruction-following capability,
// not via a separate LLM call. The Pass 1 prompt block carries the rule set;
// NB2 composes and renders the title in one shot.

import type { AtmosphereID, PlaqueMode } from './landscape-shared'
import { ATMOSPHERE_LABELS } from './landscape-shared'

// ── METADATA DETECTION ────────────────────────────────────────
// If user-supplied plaque text contains any of these patterns, the entire
// string is considered metadata-shaped and is rejected (mode demotes to off).
// Conservative on purpose — we'd rather reject a borderline title than render
// "Screenshot 2026-04-22 063114" on a museum plaque.
const METADATA_PATTERNS: RegExp[] = [
  /\bscreenshot\b/i,
  /\bimg[_-]?\d+/i,
  /\bdsc[_-]?\d+/i,
  /\bphoto[_-]?\d+/i,
  /\b\d{4}[-/.]\d{1,2}[-/.]\d{1,2}\b/,         // 2026-04-22 / 2026.04.22
  /\b\d{1,2}[-/.]\d{1,2}[-/.]\d{2,4}\b/,        // 4/22/2026
  /\b\d{1,2}:\d{2}(:\d{2})?\b/,                 // 06:31 / 06:31:14
  /\b\d{6,}\b/,                                  // bare numerics like 063114
  /\.(jpe?g|png|webp|gif|heic|tiff?|bmp|raw)\b/i,
]

export function isMetadataLike(text: string): boolean {
  return METADATA_PATTERNS.some(p => p.test(text))
}

export function sanitizePlaqueText(raw: string | undefined): string | null {
  const trimmed = (raw || '').trim()
  if (!trimmed) return null
  if (isMetadataLike(trimmed)) return null
  // Hard cap on plaque length — physical plausibility.
  // 60 chars is roughly the longest a brass plaque can hold legibly at scale.
  if (trimmed.length > 60) {
    return trimmed.slice(0, 60).trim()
  }
  return trimmed
}

// ── MODE RESOLUTION ───────────────────────────────────────────
export interface ResolvedPlaque {
  mode:    PlaqueMode    // effective mode after sanitization (may demote 'user' → 'off')
  text:    string | null // resolved user text (only set in 'user' mode)
  warning: string | null // human-readable warning if mode was demoted
}

export function resolvePlaque(input: {
  mode:    PlaqueMode | undefined
  rawText: string | undefined
}): ResolvedPlaque {
  const mode = input.mode || 'off'

  if (mode === 'off') {
    return { mode: 'off', text: null, warning: null }
  }

  if (mode === 'ai') {
    // Title is generated by NB2 at render time. No text resolution here.
    return { mode: 'ai', text: null, warning: null }
  }

  // user mode — sanitize and possibly demote.
  const sanitized = sanitizePlaqueText(input.rawText)
  if (!sanitized) {
    return {
      mode:    'off',
      text:    null,
      warning: 'Plaque text was empty or contained metadata-shaped strings (timestamps, filenames, "Screenshot", etc.). Plaque omitted for this render.',
    }
  }
  return { mode: 'user', text: sanitized, warning: null }
}

// ── PASS 1 PROMPT BLOCK ───────────────────────────────────────
// Returns the PLAQUE: block to inject into NB2's prompt.
// Returns null when mode is 'off' — caller drops the block entirely.
export function buildPass1PlaqueBlock(input: {
  mode:         PlaqueMode
  text:         string | null
  displayName?: string
  atmosphere?:  AtmosphereID
}): string | null {
  if (input.mode === 'off') return null

  if (input.mode === 'user' && input.text) {
    const safe = input.text.replace(/"/g, '\\"')
    return `PLAQUE:
A small brass plaque is mounted on the front rim of the walnut plinth. The plaque is brushed brass or aged bronze, physically embedded, properly scaled, and engraved (never printed or overlaid). The plaque reads exactly: "${safe}".

Render the text clearly, legibly, and centered, in restrained engraved capitals. Do not modify, expand, paraphrase, or reinterpret the text. Do not add any other text on the plaque. Plaque text must never include timestamps, filenames, "Screenshot", system strings, or technical metadata — only the exact text given above.`
  }

  if (input.mode === 'ai') {
    const place = input.displayName?.trim()
    const atm   = input.atmosphere ? ATMOSPHERE_LABELS[input.atmosphere].toLowerCase() : ''
    const inspirationLine = (place && atm)
      ? `Take inspiration from the subject (${place}) and the lighting condition (${atm}), but the title need not name them directly.`
      : place
        ? `Take inspiration from the subject (${place}), but the title need not name it directly.`
        : atm
          ? `Take inspiration from the lighting condition (${atm}), but the title need not name it directly.`
          : 'Take inspiration from the scene itself.'

    return `PLAQUE:
A small brass plaque is mounted on the front rim of the walnut plinth. The plaque is brushed brass or aged bronze, physically embedded, properly scaled, and engraved (never printed or overlaid).

Compose a refined engraved title for the plaque following these rules exactly:
- Title Case
- 2 to 6 words total
- No numbers, no dates, no timestamps, no filenames, no technical strings
- No descriptive sentences
- Tone must be restrained, timeless, and gallery-appropriate — like a museum label
- Optional dash allowed; no other punctuation

${inspirationLine}

Render the chosen title clearly, legibly, and centered, in restrained engraved capitals. If a fitting title cannot be composed under these rules, leave the plaque surface blank rather than render placeholder text, "Untitled", or any metadata-shaped string.`
  }

  return null
}

// ── PASS 2 PROMPT BLOCK ───────────────────────────────────────
// Pass 2 (GPT-image-1 refine) does not compose titles. It either preserves
// what Pass 1 produced, or — in 'off' mode — actively suppresses any plaque
// the model might be tempted to add (it loves adding them to "miniature on
// plinth" compositions).
export function buildPass2PlaqueBlock(mode: PlaqueMode): string {
  if (mode === 'off') {
    return `PLAQUE:
There is no plaque on the plinth in this composition. Do not add a plaque, label, sign, brass plate, name tag, or any text to the plinth surface. Leave the plinth rim clean and uninterrupted.`
  }
  // user or ai — preserve whatever Pass 1 rendered.
  return `PLAQUE:
A brass plaque is present on the front rim of the plinth. Preserve its text exactly as it appears in the source image — do not modify, replace, paraphrase, or invent new text. Render the existing text more clearly and legibly while keeping the content unchanged. If the plaque appears blank in the source, keep it blank — do not invent text. Plaque text must never include timestamps, filenames, "Screenshot", or technical metadata under any circumstance.`
}
